RFM17 - Provider Record Liveness
protocol/network-measurements pull request #16
Opened 2022-08-18 17:39 UTC by cortze

This is the first draft of the report for RFM17. 

All the feedback is more than welcome, so please, go ahead and leave some comments. 😄 

I still have to merge a few branches of the [hoarder](https://github.com/cortze/ipfs-cid-hoarder), so I didn't add the GitHub submodule yet (please be patient 😅, it will come soon).

2022-08-22 15:27 UTC, guillaumemichel requested changes
Very good and well detailed report!

Great description of the Hoarder and very interesting results. Would it make sense to add a small section between the results and the conclusion discussing and suggesting which changes could be taken in order to improve IPFS, as you mentioned briefly in the conclusion? This section could contain recommendations for republish intervals, K replication parameter, Hydra nodes and the tradeoffs associated with these suggestions. The conclusion could then sum up the preferred changes described in this section.

The boxplots contain a lot of outliers stacking on top of each other. Would it be possible to have circles of different sizes according to the number of stacked outliers? This would help to visualize a bit better the outliers.  

Could you update the folder name `implementations/rfm-17-provider-record-liveness` to `implementations/rfm17-provider-record-liveness`?

2022-08-22 15:27 UTC, guillaumemichel commented on results/rfm17-provider-record-liveness.md
> +In a currently over-saturated network, where running a DHT Server is way more CPU and bandwidth consuming than a single DHT Client, any window of improvement has to be taken. Although reducing the _K
> Although reducing the _K_ value to 15 would imply a 25% overhead reduction

25% of the number of Provider Records stored on each DHT server node?

2022-08-31 10:22 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +When looking for the closest peers in the network, each client starts looking for the closest peers inside its routing table. Once they are identified, the client starts an iterative process where we
Yep, it wasn't explicitly saying the closest peers to the CIDs.
Thanks for the catch and thanks @yiannisbot for the suggestion!

2022-08-31 10:29 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +After the CID publication to the IPFS network, the tool follows up the study by tracking the activity of each _CID_ and _PR Holder_.
I was referring to the hoarding-action and study sounded good in my mind 😅   
I could leave it as `the tool follows up by tracking the activity of each _CID_ and _PR Holder_.`

2022-08-31 10:40 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +![img](../implementations/rfm-17-provider-record-liveness/plots/k20/cid_sha256_distribution_cdf.png)
Yep, I will update all the figures applying `plt.rcParams["figure.facecolor"] = "white"`

2022-08-31 10:41 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +Despite the randomness of the bytes used to generate the _CIDs_ and the homogeneousness that the _SHA256_ encoding function provides might be affected by the relatively short size of the _CID_ datase
I didn't know it, do you have any link to the method or to an example?

2022-08-31 10:48 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +<p style="text-align: center;">Table 1. Percentile table for the `Provide()` method's duration</p>
Seems that trying to center it through `HTML` + `css styles` was only working in `hackmd.io` and it also breaks the rendering of `Provide()`.
I will fix it, thanks for the catch!

2022-08-31 14:26 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +Taking a closer look at that initial drop, in Figure 27, we can see how the ratio decreases by 25% uniformly for most of the K values (clear exception of K=40 which drops to ~65%). Furthermore, we ca
when `go-libp2p-kad-dht` makes a [lookup](https://github.com/libp2p/go-libp2p-kad-dht/blob/dae5a9a5bd9c7cc8cfb5073c711bc308efad0ada/query.go#L79) to get the closest peers,  the process prioritizes peers that we heard of or the ones that were already queried:
>// query all of the top K peers we've either Heard about or have outstanding queries we're Waiting on.
	// This ensures that all of the top K results have been queried which adds to resiliency against churn for query
	// functions that carry state (e.g. FindProviders and GetValue) as well as establish connections that are needed
	// by stateless query functions (e.g. GetClosestPeers and therefore Provide and PutValue)

So my guess here is that the more peers you are looking for, the less accuracy you will get since you look beyond the K-bucket size and the process tends to prioritize active peers. 

Does it make sense?

2022-08-31 14:34 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +This pattern gets even more evident when displaying the percentage of the active _PR Holders_ (see Figure 23). Here we can clearly see that the difference between K=15 and K=40 's median is in order
I think that it is related with the comment I left in the [next discussion ](https://github.com/protocol/network-measurements/pull/16/files#r959656431)

The lookup process seems to prioritize peers that we already queried to reduce node churn, so when you have a wide set of peers "close enough" beyond the K bucket size  it seems to increase more the ratio of connected peers - with the downsizing that they are "not that close"

2022-08-31 14:42 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +With the intention of simulating a Hydra-free PRL study, we have included in the `go-libp2p-kad-dht` fork a modification that can blacklist a whole set of PeerIDs from being elected as _K_-closest pe
Yep, totally agree

2022-08-31 14:43 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +The following graphs show the client diversity achieved in the initial _PR Holders_ before and after applying the `hydra-booster` filter to the _CID Hoarder_ run. In Figure 28, we can observe that hy
Nice catch

2022-08-31 14:45 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +| Hydra-Filter OFF | Hydra-Filter ON |
True, the plotting was automated from the SQL query, and since I was ordering based on % of total share, the colors changed.

2022-08-31 15:03 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +|----|----|
I would have also expected it to be slightly bigger. Although, since they aren't many `ioi` nodes in de network and the runs were on different dates, it could happen that we got fewer identified `ioi` nodes and they are inside the `NotIdentified` stack.

2022-08-31 15:25 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +From one side, reducing _K_ to 15 would reduce by 25% the overhead in the network while decreasing the median CID publication time by a few seconds. It would imply assuming a higher chance of not bei
Yep, wasn't clear enough. Thanks, @guillaumemichel for the pointer and @yiannisbot for the suggestion.

2022-08-31 15:38 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +- In Figure 7, the total number of hops that the DHT walk needed to know that there weren't any other closest peers to the key. We can see that the 50% of the DHT-walks are done in 4 hops, and 90% of
Indeed, although I would say that the DHT lookup could be a separate report by itself (maybe an extension of this one?) 

Would be nice to tackle several points we already discussed in the OfficeHours meetings like:
which is the duration of each hop, reconstructing and visualizing each hop in the lookup, tracking the errors of each query, etc...

2022-09-01 10:02 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +This last statement is a bit trivial. Although we can assume that if the _PR Holders_ keep the records over the 24 hours the _CIDs_ are reachable, adversary events on the peer-to-peer network, like h
yep

2022-09-01 10:04 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +Finding an optimal _K_ replication value has been largely discussed for a long time in the IPFS Community. There are several discussion lines in favor of decreasing the _K_ replication value.
Seems that it only happened during verbal conversations. Maybe it's time to open the discussion ;)

2022-09-01 18:35 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +Looking at Figure 34, the number of hops it is needed to discover for the first time the closest peers doesn't differ much between both data sets. In both cases, 90% of the lookups stay at or under 4
'k=20' ->  4.546
'k=no_hydras' -> 4.764

2022-09-01 20:39 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +On the other hand, increasing _K_ to 25 would give us a higher margin of safety. Its major drawback is that it would increase the network's overhead by 25%, while adding extra seconds to the whole `P
Reducing _K_ to 15 increases the average of Hops on the retrieval side, but the difference is not that big.
These are not the same hops that we performed to retrieve the content, but the average hops to get the closest peers:
k=15 -> 4.65 hops
k=20 -> 4.54 hops
k=25 -> 4.50 hops
k=40 -> 4.40 hops

2022-09-01 20:44 UTC, cortze commented on results/rfm17-provider-record-liveness.md
> +The steady in-degree ratio measured for k=20 over +80 hours showed that the initial closest peers keep being the closest ones for more than 48 hours. This measurement dismisses any existing doubt abo
addressing it in the next iteration

2022-09-01 21:50 UTC, cortze commented
Thank you very much @yiannisbot and @guillaumemichel for the support and the feedback! 
I think I covered all the typos 🙈 , suggestions, and missing explanations. Let me know if I missed something and what you think about this second iteration🚀

2022-09-02 12:25 UTC, guillaumemichel commented on results/rfm17-provider-record-liveness.md
> +Despite the randomness of the bytes used to generate the _CIDs_ and the homogeneousness that the _SHA256_ encoding function provides might be affected by the relatively short size of the _CID_ datase
I haven't seen an implementation, but generating a random multihash (instead of hashing random data) should work too

2022-09-02 12:30 UTC, guillaumemichel commented on results/rfm17-provider-record-liveness.md
> +Taking a closer look at that initial drop, in Figure 27, we can see how the ratio decreases by 25% uniformly for most of the K values (clear exception of K=40 which drops to ~65%). Furthermore, we ca
Yes it makes sense!

2022-09-02 12:33 UTC, guillaumemichel commented on results/rfm17-provider-record-liveness.md
> +The initial light-crawler takes 5 to 7 mins to crawl the network, and finds around 1950 of the ~2000 hydra peers in the network. The remaining 0.06% of the elected hydras as _PR Holders_, are just th
OK I see

2022-09-02 12:38 UTC, guillaumemichel commented on results/rfm17-provider-record-liveness.md
> +In a currently over-saturated network, where running a DHT Server is way more CPU and bandwidth consuming than a single DHT Client, any window of improvement has to be taken. Although reducing the _K
@yiannisbot I would say that it is only the storage that gets affected. Connections and bandwidth are expected to stay the same, as each node will store 25% less Provider Records, but they will have to respond to +25% requests for each of them, as they are stored as 25% less peers. Overall, the number of requests stays the same for the content.
There will be a small bandwidth reduction for the publish operation (25%) as the content is published x15 and not x20, but I don't think that the publish operation is a big share of all requests.

2022-09-02 12:41 UTC, guillaumemichel approved these changes

2022-09-06 05:17 UTC, merged